config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  devise_for :users
    as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'jobs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
      can :manage, :all
    elsif user.role == "author"
      can :create, Review
      can :update, Review, :user_id => user.id
      can [:show, :update], User, :id => user.id
    elsif user.role == "owner"
      can :update, Venue
      can [:show, :update], User, :id => user.id
    else
      can [:show, :update], User, :id => user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  JOB_TYPES = ["1 år", "8 måneder", "6 måneder", "2 måneder"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
  def show
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user #if you don't care who the user is I recommend to use user_signed_id? method
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_user!, unless: :devise_controller?
  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /jobs
  # GET /jobs.json
  def index
    if(params.has_key?(:job_type))
      @jobs = Job.where(job_type: params[:job_type]).order("created_at desc")
    else
      @jobs = Job.all.order("created_at desc")
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    token = params[:stripeToken]
    job_type = params[:job_type]
    job_title = params[:title]


    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Your job listing was purchased successfully!' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end

    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :new
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :url, :job_type, :location, :job_author, :remote_ok, :apply_url, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def job_type(job_type)
    if job_type == "1 år"
      content_tag :span, "#{job_type}", class: "tag is-Info"
    elsif job_type == "8 måneder"
      content_tag :span, "#{job_type}", class: "tag is-Info"
    elsif job_type == "6 måneder"
      content_tag :span, "#{job_type}", class: "tag is-Info"
    elsif job_type == "2 måneder"
      content_tag :span, "#{job_type}", class: "tag is-Info"
    else
      ""
    end
  end

  def job_author(job)
    user_signed_in? && current_user.id == job.user_id
  end
end

app/views/home/index.html.erb
<h1>Welcome to <%= Rails.configuration.application_name %>!</h1>
<p class="lead">Use this document as a way to quickly start any new project by generating files, installing gems, and more. </p>

app/views/jobs/_form.html.erb
<%= simple_form_for @job, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

      <div class="field">
        <div class="control">
        <%= f.input :title, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, placeholder: "Frontend Developer" %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :apply_url, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }  %>
        </div>
      </div>


    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Job Type:</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :job_type, collection: Job::JOB_TYPES, prompt: "Select a job type" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-briefcase"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="column">

        <div class="field">
          <div class="control">
            <%= f.input :location, require: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, hint: 'Examples: "San Francisco, CA", "Seattle", "Anywhere"' %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <label for="job[remote_ok]">
              <%= f.input :remote_ok, required: false, input_html: { class: "checkbox"}, wrapper: false, label: false %>
              Work can be done remotely
            </label><i class="fa fa-wifi"></i>
          </div>
        </div>
      </div>
    </div>

      <div class="field">
        <div class="control">
          <%= f.input :description, required: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %>
        </div>
      </div>


    <div class="columns">

      <div class="field column">
        <div class="control">
          <%= f.input :job_author, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, label: "Company" %>
        </div>
      </div>

      <div class="field column">
        <div class="control">
          <%= f.input :url, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, label: "Company Website", placeholder: "http://company.com" %>
        </div>
      </div>

    </div>

    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Logo Image</label>
          <div class="file">
            <label class="file-label">
              <%= f.input :avatar, as: :file, required: false, input_html: { class:"file-input job-avatar" }, label: false, wrapper: false %>
                <span class="file-cta">
                  <span class="file-icon"><i class="fa fa-upload"></i></span>
                  <span class="file-label">Choose a file…</span>
                </span>
            </label>
          </div>
        </div>
      </div>
      <div class="column">
        <output id="list"></output>
      </div>
    </div>

    <hr />

    <%= render 'payment' %>

    <%= f.button :submit, class: "button is-primary is-large is-rounded mv4" %>

<% end %>

app/views/jobs/_panel.html.erb
<nav class="panel">
  <p class="text-uppercase has-text-gray pv1 f6">filter kampagne type</p>

  <ul class="mb3 pa0">
    <li class="pv1">
      <%= link_to 'Alle kampagner', jobs_path, class: "button is-fullwidth is-Light" %>
    </li>

    <li class="pv1">
      <%= link_to '1 år', jobs_path(job_type: "1 år"), class: "button is-fullwidth is-Dark" %>
    </li>

    <li class="pv1">
      <%= link_to '8 måneder', jobs_path(job_type: "8 måneder"), class: "button is-fullwidth is-Dark" %>
    </li>

    <li class="pv1">
      <%= link_to '6 måneder', jobs_path(job_type: "6 måneder"), class: "button is-fullwidth is-Dark"  %>
    </li>

    <li class="pv1">
      <%= link_to '2 måneder', jobs_path(job_type: "2 måneder"), class: "button is-fullwidth is-Dark" %>
    </li>
  </ul>
</nav>

<div class="info-div">

<nav class="info">
  <p class="text Infomation"><strong>Infomation og nyheder</strong></p>
      <p>Vi er stolte af at kunne præsentere vores nye menu. Du kan nu nemmere finde det du leder efter her på medlems siden. Skriv endelig hvis i har flere ting vi kan tilføje 😍</p>
</nav>

</div>

app/views/jobs/_payment.html.erb
<% if !@job.persisted? %>
  <h4 class="subtitle is-4">Payment</h4>

  <div class="notification is-light has-text-centered">
    <i class="fa fa-credit-card"></i>
    All jobs cost <strong>$300</strong> USD for 30 days.
    <span class="block mb4"></span>
  </div>

  <div class="form-row">
    <label for="card-element" class="label">
      Enter credit or debit card
    </label>

    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <% if current_user.stripe_id.present? %>
    <div class="last-card bg-light pa4 border-radius-3 mt4">
      <h5 class="is-6 title pt2">Previously used card</h5>
      <table class="table is-narrow bg-light is-fullwidth">
        <thead>
          <th>Card Brand</th>
          <th>Last 4 Digits</th>
          <th>Expiration Month</th>
          <th>Expiration Year</th>
        </thead>
        <tr>
          <td><%= current_user.card_brand %></td>
          <td><%= current_user.card_last4 %></td>
          <td><%= current_user.card_exp_month %></td>
          <td><%= current_user.card_exp_year %></td>
        </tr>
      </table>
    </div>
  <% end %>
<% end %>

app/views/jobs/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Editing Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/index.html.erb
<div class="columns border-top">
<% if user_signed_in? %>
  <div class="column is-2 bg-light">
    <div class="pl3 pr1">
      <%= render 'panel' %>
    </div>
  </div>

  <div class="column is-9 pl6">
    <% @jobs.each do |job| %>
    <div class="columns border-bottom pt4">
      <div class="column is-1">
        <% if !job.avatar.file.nil? %>
          <%= link_to image_tag(job.avatar_url(:thumb), alt: job.job_author, width: 100, height: 100), job.url %>
        <% end %>
      </div>
      <div class="column is-8">
        <h3 class="title is-4 index-title"><%= link_to job.title, job %></h3>
          <ul>
            <li><%= link_to job.job_author, job.url %></li>
          </ul>
        <div class="pv2 f6">
          <%= sanitize(job.description.truncate(200, separator: '</p>')) %>
        </div>

        <% if current_user.try(:admin) || job_author(job) %>
          <ul class="pv3">
            <li class="inline-block f6">Admin controls: </li>
            <li class="inline-block">
              <%= link_to 'View', job, class: 'button is-small is-link is-outlined' %></li>
            <li class="inline-block">
              <%= link_to 'Edit', edit_job_path(job), class: 'button is-small is-link is-outlined' %></li>
            <li class="inline-block">
              <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-link is-outlined' %></li>
          </ul>
        <% end %>

        </div>
        <div class="column has-text-right">
          <%= job_type(job.job_type) %>
          <p class="pt2 f6"><%= job.location %></p>
        </div>
      </div>
    <% end %>
  </div>
  <% else %>
  <div class="notli">
    <p>
      Upps, du var lidt for hurtig, du skal først være logget ind.
      <div class="logindud">
      <a class="button is-primary" href="http://localhost:3000/users/sign_in">Log ind 🤗</a>
      <a class="button is-primary" href="http://localhost:3000/users/sign_up">Opret dig nu 😍</a>
        </div>
    </p>
  </div>
  </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Post new Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/show.html.erb
<% if user_signed_in? %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" rel="stylesheet"/>
  <div class="columns pt4 pb7">
    <div class="column is-7 is-offset-1">

      <h1 class="title is-2"><%= @job.title %></h1>

      <ul class="list pb4">
        <li class="inline-block f6 pr2"><%= job_type(@job.job_type) %></li>
        <li class="inline-block f6 ph2"><i class="fa fa-pin"></i> <%= @job.location %></li>
        <% if @job.remote_ok? %>
          <li class="inline-block f6 ph2"><i class="fa fa-wifi"></i> Remote Job</li>
        <% end %>
      </ul>

      <div class="content text-serif f4">
        <%= @job.description.html_safe %>
      </div>

      <%= link_to 'Ansøg til kampagne', @job.apply_url, class:"button is-rounded is-large is-fullwidth is-link" %>

    </div>



    <div class="column is-2 is-offset-1 has-text-centered">

      <% if !@job.avatar.file.nil? %>
        <%= link_to image_tag(@job.avatar_url(:thumb), alt: @job.job_author, class: "has-text-centered"), @job.url %>
      <% end %>

      <h5 class="is-5 has-text-centered"><%= link_to @job.job_author %></h5>

      <% if current_user.try(:admin) || job_author(@job) %>
        <ul class="pv3">
          <li class="pv1 f6">Admin controls: </li>
          <li class="pv1 inline-block">
            <%= link_to 'View', @job, class: 'button is-small is-link is-outlined' %></li>
          <li class="pv1 inline-block">
            <%= link_to 'Edit', edit_job_path(@job), class: 'button is-small is-link is-outlined' %></li>
          <li class="pv1 inline-block">
            <%= link_to 'Delete', @job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-link is-outlined' %></li>
        </ul>
      <% end %>
    </div>
  </div>

    <script type="text/javascript" src="https://heyad.formstack.com/forms/js.php/kampagne"></script><noscript><a href="https://heyad.formstack.com/forms/kampagne" title="Online Form">Online Form - Kampagne</a></noscript>
    <% else %>
    <div class="notlijobs">
      <p>
        Upps, du var lidt for hurtig, du skal først være logget ind.
        <div class="logindud">
        <a class="button is-primary" href="http://localhost:3000/users/sign_in">Log ind 🤗</a>
        <a class="button is-primary" href="http://localhost:3000/users/sign_up">Opret dig nu 😍</a>
          </div>
      </p>
    </div>
    </div>
  <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:title) %>
  <%= content_for(:title) %>
<% else %>
  <title>HeyAd - Medlems side</title>
<% end %>
    <link rel="shortcut icon" href="http://heyad.dk/wp-content/uploads/2018/04/Egenligt_logo.png"/>
    <script src="https://wchat.freshchat.com/js/widget.js"></script>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" rel="stylesheet"/>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application.js" %>

    <%= tag :meta, name: "stripe-public-key", content: Figaro.env.stripe_publishable_key %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
<% if user_signed_in? %>
    <nav class="navbar ">
      <div class="navbar-brand">
        <a class="navbar-item" href="http://localhost:3000">
          <img src="http://heyad.dk/wp-content/uploads/2018/04/Egenligt_logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="32" height="75">
        </a>

        <a class="navbar-item" href="https://github.com/jgthms/bulma" target="_blank">
          <span class="icon" style="color: #333;">
            <i class="fa fa-instagram"></i>
          </span>
        </a>

        <a class="navbar-item" href="https://github.com/jgthms/bulma" target="_blank">
          <span class="icon" style="color: #333;">
            <i class="fa fa-facebook"></i>
          </span>
        </a>

             <span class="navbar-burger burger" data-target="navbarMenuHeroA">
               <span></span>
               <span></span>
               <span></span>
             </span>
           </div>
           <div id="navbarMenuHeroA" class="navbar-menu">
             <div class="navbar-end">
               <a class="navbar-item " href="http://bulma.io/expo/">
                 <span class="bd-emoji">🆘</span> &nbsp;FAQ
               </a>
               <a class="navbar-item " href="http://bulma.io/expo/">
                 <span class="bd-emoji">🎨</span> &nbsp;Expo
               </a>
               <a class="navbar-item " href="http://bulma.io/expo/">
                 <span class="bd-emoji">🎨</span> &nbsp;Expo
               </a>
               <div class="navbar-item has-dropdown is-hoverable">
                 <%= link_to 'Din konto', edit_user_registration_path, class: "navbar-link" %>
                 <div class="navbar-dropdown is-right">
                   <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                   <%= link_to "Log Ud 🔒", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                 </div>

                   </div>
                 </div>
               </div>
               <div class="navbar-end">
             </div>
           </div>
         </div>
       </nav>
    <section class="hero is-primary">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            Vi sidder klar på livechatten ⌨️
          </h1>
          <h2 class="subtitle">
            Vi ønsker dig en rigtig god dag 🙊
          </h2>
        </div>
      </div>
    </section>
  <% else %>
  <nav class="navbar ">
    <div class="navbar-brand">
      <a class="navbar-item" href="http://localhost:3000">
        <img src="http://heyad.dk/wp-content/uploads/2018/04/Egenligt_logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="32" height="75">
      </a>

      <a class="navbar-item" href="https://github.com/jgthms/bulma" target="_blank">
        <span class="icon" style="color: #333;">
          <i class="fa fa-instagram"></i>
        </span>
      </a>

      <a class="navbar-item" href="https://github.com/jgthms/bulma" target="_blank">
        <span class="icon" style="color: #333;">
          <i class="fa fa-facebook"></i>
        </span>
      </a>

           <span class="navbar-burger burger" data-target="navbarMenuHeroA">
             <span></span>
             <span></span>
             <span></span>
           </span>
         </div>
         <div id="navbarMenuHeroA" class="navbar-menu">
           <div class="navbar-end">
             <a class="navbar-item " href="http://localhost:3000/users/sign_in">
               <span class="bd-emoji">🤗</span> &nbsp;Log ind
             </a>
             <a class="navbar-item " href="http://localhost:3000/users/sign_up">
               <span class="bd-emoji">😍</span> &nbsp;Opret konto
             </a>
                 </div>
               </div>
             </div>
             <div class="navbar-end">
           </div>
         </div>
       </div>
     </nav>
<% end %>

  <%= yield %>

  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
         <a href="https://web-crunch.com" target="_blank">Heyad.dk</a> Denne side er pt i BETA så fejl kan opstå. Ved fejl skriv endelig til os.
        </p>
      </div>
    </div>
  </footer>
  <script>
  window.fcWidget.init({
    token: "935ad2ba-0bf5-498a-bf55-187f7c62e2eb",
    host: "https://wchat.freshchat.com"
  });
</script>
  </body>
</html>